# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mrhomero
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mrhomero-api
service: mrhomero-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    NODE_ENV: ${env:NODE_ENV}

    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_PORT: ${env:DB_PORT}
    DB_DIALECT: ${env:DB_DIALECT}

    DB_TEST_USER: ${env:DB_TEST_USER}
    DB_TEST_PASS: ${env:DB_TEST_PASS}
    DB_TEST_NAME: ${env:DB_TEST_NAME}
    DB_TEST_HOST: ${env:DB_TEST_HOST}
    DB_TEST_PORT: ${env:DB_TEST_PORT}
    DB_TEST_DIALECT: ${env:DB_TEST_DIALECT}
    
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_USER: ${env:EMAIL_USER}
    FRONTEND_URL: ${env:FRONTEND_URL}
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    PORT: ${env:PORT}

functions:
  api:
    handler: server.handler
    events:
      - httpApi:
          path: /{proxy+} 
          method: '*'

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - .env
    - README.md

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
